name: wmake

on:
  [push, pull_request]:
    branches:
      - master
    paths:
      - 'applications/solvers/heatTransfer/directChillFoam/**'
      - 'src/fvConstraints/**'
      - 'src/fvModels/**'
      - 'src/ThermophysicalTransportModels/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: wmake
    steps:
    - uses: actions/checkout@v3

    - name: Cache OpenFOAM 9
      id: cache-OF9
      uses: actions/cache@v3
      with:
        path: |
          /opt/openfoam9
        key: ${{ runner.os }}-OF9
    
    - if: ${{ steps.cache-OF9.outputs.cache-hit == 'true' }}
      name: OF9 cache hit
      continue-on-error: true
      run: |
        echo OpenFOAM 9 already installed
        ls /opt/openfoam9/wmake

    - name: Install OpenFOAM 9
      shell: bash
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        sudo apt-get -y install openfoam9

    - name: Append OF environment variables to .bashrc 
      shell: bash
      working-directory: ${{runner.workspace}}
      continue-on-error: true
      run: |
        echo source /opt/openfoam9/etc/bashrc >> ~/.bashrc
        source ~/.bashrc
        which wmake
  
    - name: wmake fvConstraints
      shell: bash
      working-directory: src/fvConstraints
      continue-on-error: true
      run: |
        source /opt/openfoam9/etc/bashrc
        wmake libso
    
    - name: wmake fvModels
      shell: bash
      working-directory: src/fvModels
      continue-on-error: true
      run: |
        source /opt/openfoam9/etc/bashrc
        wmake libso
    
    - name: wmake ThermophysicalTransportModels
      shell: bash
      working-directory: src/ThermophysicalTransportModels
      continue-on-error: true
      run: |
        source /opt/openfoam9/etc/bashrc
        wmake libso

    - name: wmake multicomponentAlloy
      shell: bash
      working-directory: applications/solvers/heatTransfer/directChillFoam/multicomponentAlloy
      continue-on-error: true
      run: |
        source /opt/openfoam9/etc/bashrc
        wmake libso
    
    - name: wmake directChillFoam
      shell: bash
      working-directory: applications/solvers/heatTransfer/directChillFoam
      continue-on-error: true
      run: |
        source /opt/openfoam9/etc/bashrc
        wmake
